---
title: "Untitled"
output: html_document
date: "2022-11-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(circlize)
```

```{r}
data=read.csv("Combined_data.csv",header = T)
df_mat=data.matrix(data)
row.names(df_mat)=data$Gene_name
df_mat=df_mat[,-c(1,2)]
```

```{r}
col_fun = colorRamp2(c(0, 0.2, 5), c("red", "green", "darkgreen"))
col_direction=c("axon development" = "red", "neuron projection development"	= "blue", "neuron development" = "green","axonogenesis" = "black","generation of neurons" = "darkorchid4","neuron differentiation" = "orange","nervous system development" = "magenta","structural constituent of cytoskeleton" = "maroon4","neurogenesis" = "lightblue4","positive regulation of cell motility" = "deeppink2","Regulation of cellular component movement" = "goldenrod4","regulation of cell migration" = "cadetblue4","central nervous system neuron differentiation" = "snow4")
direction=data$Pathway
split=as.factor(data$Pathway)
```

#creating a function for circular heat map
```{r}
circlize_plot_2 = function() {
  circos.par("start.degree" = 90, gap.degree = 3)
  circos.heatmap(df_mat[,1:2], split = split, col = col_fun,cell.border = "black", rownames.side = "outside",track.height = 0.03, bg.border = "black" ,na.col = "white")
  circos.heatmap(df_mat[,3:8], split = split, col = col_fun,cell.border = "black",track.height = 0.1, bg.border = "black" ,na.col = "white")
  circos.heatmap(df_mat[,9:17], split = split, col = col_fun,cell.border = "black",track.height = 0.1, bg.border = "black",na.col = "white")
  circos.heatmap(df_mat[,18:21], split = split, col = col_fun,cell.border = "black",track.height = 0.05, bg.border = "black",na.col = "white")
  circos.heatmap(df_mat[,22:25], split = split, col = col_fun,cell.border = "black",track.height = 0.03, bg.border = "black",na.col = "white")
  circos.heatmap(df_mat[,26:31], split = split, col = col_fun,cell.border = "black",track.height = 0.05, bg.border = "black",dend.side = "inside",na.col = "white")
  circos.heatmap(direction, col = col_direction, track.height = 0.01)
  circos.clear()
}
```

#Plot the circular heat map
```{r}
png(filename="CircularHeatmaP_combined.png",bg = "white",res = 300,units =  "in" ,width = 18, height = 18)
circlize_plot_2()
dev.off()
```
